### ISSUE TITLE
[Error]: While selfhosting i am getting this error

### ISSUE THREAD

**Issue by anujpflash** [eduardozgz/member-counter-bot#163]
```
Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
      at GatewayClient.exports.default (./dist/src/utils/commandHandler.js:43:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:93:5)
}  reason:  TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at GatewayClient.exports.default (./dist/src/utils/commandHandler.js:43:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
 ```
 Any way to resolve it? I got the priviliged intents but idk why this is happening

**Comment by eduardozgz** [comment]
Please, join the support server: https://discord.gg/g4MfV6N
